function datasets = getDatasetNamesUCR43    

    datasets = {        
        '50words'
        'Adiac'
        'Beef'
        'CBF'
        'ChlorineConcentration'
        'CinC_ECG_torso'
        'Coffee'
        'Cricket_X'
        'Cricket_Y'
        'Cricket_Z'
        'DiatomSizeReduction'
        'ECG200'
        'ECGFiveDays'
        'FISH'
        'FaceAll'
        'FaceFour'
        'FacesUCR'
        'Gun_Point'
        'Haptics'
        'InlineSkate'
        'ItalyPowerDemand'
        'Lighting2'
        'Lighting7'
        'MALLAT'
        'MedicalImages'
        'MoteStrain'
        'OSULeaf'
        'OliveOil'
        'SonyAIBORobotSurface'
        'SonyAIBORobotSurfaceII'
        'StarLightCurves'
        'SwedishLeaf'
        'Symbols'
        'Trace'
        'TwoLeadECG'
        'Two_Patterns'
        'WordsSynonyms'
        'synthetic_control'
        'uWaveGestureLibrary_X'
        'uWaveGestureLibrary_Y'
        'uWaveGestureLibrary_Z'
        'wafer'
        'yoga'    
     };
    
